# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='grade',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='school_name',
            field=models.CharField(default='', max_length=16),
        ),
    ]
