# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0003_teacherinfo_range_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'verbose_name': '\u8001\u5e08\u4fe1\u606f\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='course_teacher',
            field=models.CharField(default='', max_length=64, verbose_name='\u6559\u6388\u8bfe\u7a0b'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='email',
            field=models.CharField(max_length=32, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='grade',
            field=models.CharField(default='', max_length=16, verbose_name='\u5b66\u5386'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='hobby',
            field=models.CharField(max_length=32, verbose_name='\u7231\u597d'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='moto',
            field=models.CharField(max_length=32, verbose_name='\u4eba\u751f\u683c\u8a00'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='name',
            field=models.CharField(max_length=16, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='school_name',
            field=models.CharField(default='', max_length=16, verbose_name='\u6bd5\u4e1a\u5b66\u6821'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='study_direction',
            field=models.CharField(max_length=64, verbose_name='\u7814\u7a76\u65b9\u5411'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='title',
            field=models.CharField(max_length=16, verbose_name='\u804c\u4f4d'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='work_experice',
            field=models.CharField(max_length=32, verbose_name='\u5de5\u4f5c\u7ecf\u5386'),
        ),
        migrations.AlterModelTable(
            name='teacherinfo',
            table='django_web_teacherinfo',
        ),
    ]
