# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0004_auto_20181110_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'verbose_name': '\u8001\u5e08\u4fe1\u606f'},
        ),
    ]
