# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0006_auto_20181110_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='\u8001\u5e08\u5206\u7c7b')),
            ],
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='photo',
            field=models.ImageField(default='', upload_to='uploadImages', verbose_name='\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='teachercategory',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='django_web.TeacherInfo'),
        ),
    ]
