# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0007_auto_20181111_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='extratitle',
            field=models.CharField(default='', max_length=16, verbose_name='\u804c\u4f4d'),
        ),
    ]
