# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 07:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0008_teacherinfo_extratitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u6b63\u6587')),
            ],
        ),
    ]
