# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0009_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='photoby',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 11, 7, 50, 28, 190680)),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_person',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='\u6807\u9898'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_pic',
            field=models.ImageField(default='', upload_to='uploadImages', verbose_name='\u5934\u90e8\u56fe\u7247'),
        ),
    ]
