# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0010_auto_20181111_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 11, 8, 52, 56, 128682)),
        ),
    ]
