# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0011_auto_20181111_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='\u65b0\u95fb\u5206\u7c7b')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='article',
            field=models.ManyToManyField(blank=True, to='django_web.Article'),
        ),
    ]
