# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0016_auto_20190502_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u65b0\u95fb', 'verbose_name_plural': '\u65b0\u95fb'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': '\u65b0\u95fb\u5206\u7c7b', 'verbose_name_plural': '\u65b0\u95fb\u5206\u7c7b'},
        ),
        migrations.AlterField(
            model_name='article',
            name='duration',
            field=models.CharField(default='', max_length=64, verbose_name='\u6301\u7eed\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='introduction',
            field=models.CharField(default='', max_length=128, verbose_name='\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(default='', max_length=64, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_person',
            field=models.CharField(default='', max_length=64, verbose_name='\u53d1\u5e03\u8005'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='article',
            field=models.ManyToManyField(blank=True, to='django_web.Article', verbose_name='\u65b0\u95fb'),
        ),
        migrations.AlterField(
            model_name='teachercategory',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='django_web.TeacherInfo', verbose_name='\u8001\u5e08\u59d3\u540d'),
        ),
    ]
