# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0017_auto_20190502_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachercategory',
            options={'verbose_name': '\u8001\u5e08\u5206\u7c7b', 'verbose_name_plural': '\u8001\u5e08\u5206\u7c7b'},
        ),
    ]
